import json
from typing import Any, Dict, List, Iterable, Optional, Tuple
from pydantic import BaseModel, Field


class FieldMetadata(BaseModel):
    """Field metadata model."""

    data_type: str
    description: Optional[str] = None


class ActionPlan(BaseModel):
    """What action to take if test_condition"""

    if_proven: str
    if_disproven: str


class RelationMetadata(BaseModel):
    """Relation metadata model. Will be generated by the Relation Mapper agent."""

    relation_column: List[str]
    relation: Optional[str] = None


class InsightCloudMetadata(BaseModel):
    """Insight Cloud Metadata model."""

    description: str
    hypothesis: str
    relevant_columns: List[str]
    sql: Optional[str] = None
    test_condition: str
    action: ActionPlan


class TableMetadata(BaseModel):
    """Table Metadata model."""

    table_name: str
    fields: Dict[str, FieldMetadata]
    relations: Optional[Dict[str, RelationMetadata]] = None
    insights: Optional[Dict[str, InsightCloudMetadata]] = None


class TableLite(BaseModel):
    """Light weight table metadata"""

    table_name: str
    columns: List[str]
    insights: Optional[Dict[str, InsightCloudMetadata]] = None


class LiteSchemaMetadata(BaseModel):
    """Light weight schema metadata"""

    schema_name: str
    entities: Dict[str, TableLite]


class SchemaMetadata(BaseModel):
    """Schema Metadata  model."""

    schema_name: str
    entities: Dict[str, TableMetadata]
    schema_doc: Optional[str] = None

    def simplify(self) -> LiteSchemaMetadata:
        """
        Create a lightweight version of the current SchemaMetadata:
        - Keeps only table_name, columns, and insights.
        - Removes field details and relations.
        """
        simplified_entities = {}

        for table_name, table_data in self.entities.items():
            columns = list(table_data.fields.keys())
            simplified_entities[table_name] = TableLite(
                table_name=table_data.table_name,
                columns=columns,
                insights=table_data.insights,
            )

        return LiteSchemaMetadata(
            schema_name=self.schema_name,
            entities=simplified_entities,
        )

    def filter_tables(self, table_names: list[str]):
        """
        Return a new SchemaMetadata object containing only the specified tables.
        Drops all other tables.
        """
        filtered_entities = {
            name: table for name, table in self.entities.items() if name in table_names
        }

        return SchemaMetadata(
            schema_name=self.schema_name,
            entities=filtered_entities,
            schema_doc=self.schema_doc,
        )


class DatabaseResult(BaseModel):
    """
    Database query result model with helpers to normalize raw agent/tool outputs.

    Fields:
      - sql: original SQL string or object that produced the result
      - columns: ordered list of column names
      - rows: list of rows; each row can be a dict (mapping col->val) or a tuple/list

    Helpers:
      - from_raw(raw) -> DatabaseResult: coerce a single raw item to a DatabaseResult
      - normalize_list(raw_results) -> List[DatabaseResult]: coerce many
      - to_dataframe() -> pandas.DataFrame
      - rows_as_tuples() -> List[Tuple]
    """

    sql: Any = ""
    columns: List[str] = Field(default_factory=list)
    rows: List[Any] = Field(default_factory=list)

    model_config = {"extra": "allow"}  # permit unexpected keys when validating

    # ---------- Normalization / Factory methods ----------
    @classmethod
    def from_raw(cls, raw: Any) -> "DatabaseResult":
        """
        Coerce a single raw result into a DatabaseResult instance.

        Accepts:
          - DatabaseResult -> returns it
          - dict -> expects keys like 'sql', 'columns' or 'column', 'rows' or 'data'
          - str -> tries to parse JSON; otherwise treats it as an SQL/text fallback
          - other -> attempts model_validate, otherwise fallback to a minimal object
        """
        # Already the right type
        if isinstance(raw, cls):
            return raw

        # dict-like input
        if isinstance(raw, dict):
            # tolerate multiple possible key names
            cols = (
                raw.get("columns")
                or raw.get("column")
                or raw.get("cols")
                or raw.get("colnames")
                or []
            )
            rows = raw.get("rows") or raw.get("data") or raw.get("results") or []
            sql = raw.get("sql") or raw.get("query") or raw.get("sql_text") or ""
            # If rows are dicts and columns is empty, infer columns from first row
            if not cols and rows and isinstance(rows[0], dict):
                cols = list(rows[0].keys())
            try:
                return cls(sql=sql, columns=list(cols), rows=rows)
            except Exception:
                # fallback to model_validate to preserve any extra fields
                try:
                    return cls.model_validate(raw)
                except Exception:
                    return cls(sql=sql, columns=list(cols), rows=rows)

        # string input: try JSON
        if isinstance(raw, str):
            try:
                parsed = json.loads(raw)
                return cls.from_raw(parsed)
            except Exception:
                # treat as SQL or plain text
                return cls(sql=raw, columns=[], rows=[])

        # Try pydantic coercion for other mapping-like objects
        try:
            return cls.model_validate(raw)
        except Exception:
            # last fallback
            return cls(sql=str(raw), columns=[], rows=[])

    @classmethod
    def normalize_list(cls, raw_results: Optional[Any]) -> List["DatabaseResult"]:
        """
        Normalize whatever the agent/tool returned into a list of DatabaseResult instances.
        - If raw_results is None -> returns []
        - If single item -> wraps into list
        - If iterable -> coerces each element
        """
        if raw_results is None:
            return []

        # If a single item is passed (DatabaseResult / dict / str), wrap it
        if isinstance(raw_results, (cls, dict, str)):
            raw_results = [raw_results]

        # If it's an iterable (list/tuple/etc.) iterate; otherwise coerce single element
        normalized: List[DatabaseResult] = []
        if isinstance(raw_results, Iterable):
            for r in raw_results:
                normalized.append(cls.from_raw(r))
        else:
            normalized.append(cls.from_raw(raw_results))

        return normalized

    # ---------- Convenience helpers ----------
    def to_dataframe(self):
        """
        Return a pandas.DataFrame view of the result.
        Handles rows as list-of-dicts (RealDictCursor) or list-of-tuples.
        """
        import pandas as pd

        if not self.rows:
            return pd.DataFrame(columns=self.columns)

        first = self.rows[0]
        if isinstance(first, dict):
            df = pd.DataFrame(self.rows)
            # ensure column order matches self.columns if available
            if self.columns:
                df = df.reindex(columns=self.columns)
            return df
        else:
            # assume sequence-like rows
            return pd.DataFrame(self.rows, columns=self.columns)

    def rows_as_tuples(self) -> List[Tuple]:
        """
        Return rows as list of tuples in the order of self.columns.
        Works whether rows are dicts or tuples.
        """
        out: List[Tuple] = []
        for r in self.rows:
            if isinstance(r, dict):
                out.append(tuple(r.get(c) for c in self.columns))
            else:
                out.append(tuple(r))
        return out
